[2021-12-18 13:25:06,975] {taskinstance.py:876} INFO - Dependencies all met for <TaskInstance: rank_update.mv_indicator_to_repo 2021-12-18T13:24:59.998561+00:00 [queued]>
[2021-12-18 13:25:06,980] {taskinstance.py:876} INFO - Dependencies all met for <TaskInstance: rank_update.mv_indicator_to_repo 2021-12-18T13:24:59.998561+00:00 [queued]>
[2021-12-18 13:25:06,980] {taskinstance.py:1067} INFO - 
--------------------------------------------------------------------------------
[2021-12-18 13:25:06,980] {taskinstance.py:1068} INFO - Starting attempt 1 of 1
[2021-12-18 13:25:06,981] {taskinstance.py:1069} INFO - 
--------------------------------------------------------------------------------
[2021-12-18 13:25:06,994] {taskinstance.py:1087} INFO - Executing <Task(BashOperator): mv_indicator_to_repo> on 2021-12-18T13:24:59.998561+00:00
[2021-12-18 13:25:06,995] {standard_task_runner.py:52} INFO - Started process 17647 to run task
[2021-12-18 13:25:07,003] {standard_task_runner.py:76} INFO - Running: ['airflow', 'tasks', 'run', 'rank_update', 'mv_indicator_to_repo', '2021-12-18T13:24:59.998561+00:00', '--job-id', '109', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/rank_update.py', '--cfg-path', '/tmp/tmp31o1px86', '--error-file', '/tmp/tmp2hkes6fw']
[2021-12-18 13:25:07,003] {standard_task_runner.py:77} INFO - Job 109: Subtask mv_indicator_to_repo
[2021-12-18 13:25:07,050] {logging_mixin.py:104} INFO - Running <TaskInstance: rank_update.mv_indicator_to_repo 2021-12-18T13:24:59.998561+00:00 [running]> on host airflowvm
[2021-12-18 13:25:07,193] {taskinstance.py:1280} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=rank_update
AIRFLOW_CTX_TASK_ID=mv_indicator_to_repo
AIRFLOW_CTX_EXECUTION_DATE=2021-12-18T13:24:59.998561+00:00
AIRFLOW_CTX_DAG_RUN_ID=manual__2021-12-18T13:24:59.998561+00:00
[2021-12-18 13:25:07,197] {subprocess.py:52} INFO - Tmp dir root location: 
 /tmp
[2021-12-18 13:25:07,198] {subprocess.py:63} INFO - Running command: ['bash', '-c', 'mv /home/airflow/airflow/result/html/20211218.html /home/airflow/Test/rank.md']
[2021-12-18 13:25:07,208] {subprocess.py:75} INFO - Output:
[2021-12-18 13:25:07,211] {subprocess.py:79} INFO - mv: cannot stat '/home/airflow/airflow/result/html/20211218.html': No such file or directory
[2021-12-18 13:25:07,211] {subprocess.py:83} INFO - Command exited with return code 1
[2021-12-18 13:25:07,230] {taskinstance.py:1481} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/sandbox/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 1137, in _run_raw_task
    self._prepare_and_execute_task_with_callbacks(context, task)
  File "/home/airflow/sandbox/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 1311, in _prepare_and_execute_task_with_callbacks
    result = self._execute_task(context, task_copy)
  File "/home/airflow/sandbox/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 1341, in _execute_task
    result = task_copy.execute(context=context)
  File "/home/airflow/sandbox/lib/python3.8/site-packages/airflow/operators/bash.py", line 180, in execute
    raise AirflowException('Bash command failed. The command returned a non-zero exit code.')
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code.
[2021-12-18 13:25:07,232] {taskinstance.py:1524} INFO - Marking task as FAILED. dag_id=rank_update, task_id=mv_indicator_to_repo, execution_date=20211218T132459, start_date=20211218T132506, end_date=20211218T132507
[2021-12-18 13:25:07,295] {local_task_job.py:151} INFO - Task exited with return code 1
