[2021-12-18 11:03:20,950] {taskinstance.py:876} INFO - Dependencies all met for <TaskInstance: rank_update.mv_indicator_to_repo 2021-12-18T11:00:07.858161+00:00 [queued]>
[2021-12-18 11:03:20,955] {taskinstance.py:876} INFO - Dependencies all met for <TaskInstance: rank_update.mv_indicator_to_repo 2021-12-18T11:00:07.858161+00:00 [queued]>
[2021-12-18 11:03:20,956] {taskinstance.py:1067} INFO - 
--------------------------------------------------------------------------------
[2021-12-18 11:03:20,956] {taskinstance.py:1068} INFO - Starting attempt 3 of 3
[2021-12-18 11:03:20,956] {taskinstance.py:1069} INFO - 
--------------------------------------------------------------------------------
[2021-12-18 11:03:20,970] {taskinstance.py:1087} INFO - Executing <Task(BashOperator): mv_indicator_to_repo> on 2021-12-18T11:00:07.858161+00:00
[2021-12-18 11:03:20,972] {standard_task_runner.py:52} INFO - Started process 3058 to run task
[2021-12-18 11:03:20,977] {standard_task_runner.py:76} INFO - Running: ['airflow', 'tasks', 'run', 'rank_update', 'mv_indicator_to_repo', '2021-12-18T11:00:07.858161+00:00', '--job-id', '95', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/rank_update.py', '--cfg-path', '/tmp/tmpobmb40ci', '--error-file', '/tmp/tmpamfz7kgs']
[2021-12-18 11:03:20,978] {standard_task_runner.py:77} INFO - Job 95: Subtask mv_indicator_to_repo
[2021-12-18 11:03:21,015] {logging_mixin.py:104} INFO - Running <TaskInstance: rank_update.mv_indicator_to_repo 2021-12-18T11:00:07.858161+00:00 [running]> on host airflowvm
[2021-12-18 11:03:21,156] {taskinstance.py:1280} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=rank_update
AIRFLOW_CTX_TASK_ID=mv_indicator_to_repo
AIRFLOW_CTX_EXECUTION_DATE=2021-12-18T11:00:07.858161+00:00
AIRFLOW_CTX_DAG_RUN_ID=manual__2021-12-18T11:00:07.858161+00:00
[2021-12-18 11:03:21,157] {subprocess.py:52} INFO - Tmp dir root location: 
 /tmp
[2021-12-18 11:03:21,158] {subprocess.py:63} INFO - Running command: ['bash', '-c', 'mv /home/airflow/airflow/result/html/20211218.html /home/airflow/Test/rank.md']
[2021-12-18 11:03:21,164] {subprocess.py:75} INFO - Output:
[2021-12-18 11:03:21,169] {subprocess.py:79} INFO - mv: cannot stat '/home/airflow/airflow/result/html/20211218.html': No such file or directory
[2021-12-18 11:03:21,169] {subprocess.py:83} INFO - Command exited with return code 1
[2021-12-18 11:03:21,175] {taskinstance.py:1481} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/sandbox/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 1137, in _run_raw_task
    self._prepare_and_execute_task_with_callbacks(context, task)
  File "/home/airflow/sandbox/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 1311, in _prepare_and_execute_task_with_callbacks
    result = self._execute_task(context, task_copy)
  File "/home/airflow/sandbox/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 1341, in _execute_task
    result = task_copy.execute(context=context)
  File "/home/airflow/sandbox/lib/python3.8/site-packages/airflow/operators/bash.py", line 180, in execute
    raise AirflowException('Bash command failed. The command returned a non-zero exit code.')
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code.
[2021-12-18 11:03:21,180] {taskinstance.py:1524} INFO - Marking task as FAILED. dag_id=rank_update, task_id=mv_indicator_to_repo, execution_date=20211218T110007, start_date=20211218T110320, end_date=20211218T110321
[2021-12-18 11:03:21,230] {local_task_job.py:151} INFO - Task exited with return code 1
