[2021-12-18 15:42:03,890] {taskinstance.py:876} INFO - Dependencies all met for <TaskInstance: rank_update.make_indicator 2021-12-18T15:39:07.013906+00:00 [queued]>
[2021-12-18 15:42:03,899] {taskinstance.py:876} INFO - Dependencies all met for <TaskInstance: rank_update.make_indicator 2021-12-18T15:39:07.013906+00:00 [queued]>
[2021-12-18 15:42:03,899] {taskinstance.py:1067} INFO - 
--------------------------------------------------------------------------------
[2021-12-18 15:42:03,900] {taskinstance.py:1068} INFO - Starting attempt 2 of 2
[2021-12-18 15:42:03,901] {taskinstance.py:1069} INFO - 
--------------------------------------------------------------------------------
[2021-12-18 15:42:03,913] {taskinstance.py:1087} INFO - Executing <Task(BashOperator): make_indicator> on 2021-12-18T15:39:07.013906+00:00
[2021-12-18 15:42:03,914] {standard_task_runner.py:52} INFO - Started process 21877 to run task
[2021-12-18 15:42:03,925] {standard_task_runner.py:76} INFO - Running: ['airflow', 'tasks', 'run', 'rank_update', 'make_indicator', '2021-12-18T15:39:07.013906+00:00', '--job-id', '122', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/rank_update.py', '--cfg-path', '/tmp/tmpyjpfwlnp', '--error-file', '/tmp/tmpe1_lxuz1']
[2021-12-18 15:42:03,927] {standard_task_runner.py:77} INFO - Job 122: Subtask make_indicator
[2021-12-18 15:42:03,970] {logging_mixin.py:104} INFO - Running <TaskInstance: rank_update.make_indicator 2021-12-18T15:39:07.013906+00:00 [running]> on host airflowvm
[2021-12-18 15:42:04,045] {taskinstance.py:1280} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=rank_update
AIRFLOW_CTX_TASK_ID=make_indicator
AIRFLOW_CTX_EXECUTION_DATE=2021-12-18T15:39:07.013906+00:00
AIRFLOW_CTX_DAG_RUN_ID=manual__2021-12-18T15:39:07.013906+00:00
[2021-12-18 15:42:04,046] {subprocess.py:52} INFO - Tmp dir root location: 
 /tmp
[2021-12-18 15:42:04,046] {subprocess.py:63} INFO - Running command: ['bash', '-c', 'python3 /home/airflow/parser4Study/multiple_parser.py /home/airflow/AlgorithmStudy_211124/211221/']
[2021-12-18 15:42:04,050] {subprocess.py:75} INFO - Output:
[2021-12-18 15:42:04,580] {subprocess.py:79} INFO - Traceback (most recent call last):
[2021-12-18 15:42:04,580] {subprocess.py:79} INFO -   File "/home/airflow/parser4Study/multiple_parser.py", line 69, in <module>
[2021-12-18 15:42:04,580] {subprocess.py:79} INFO -     multiple_parser.loads_and_combine_with_markdown()
[2021-12-18 15:42:04,580] {subprocess.py:79} INFO -   File "/home/airflow/parser4Study/multiple_parser.py", line 49, in loads_and_combine_with_markdown
[2021-12-18 15:42:04,580] {subprocess.py:79} INFO -     for dir_name in os.listdir('./result'):
[2021-12-18 15:42:04,580] {subprocess.py:79} INFO - FileNotFoundError: [Errno 2] No such file or directory: './result'
[2021-12-18 15:42:04,620] {subprocess.py:83} INFO - Command exited with return code 1
[2021-12-18 15:42:04,625] {taskinstance.py:1481} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/sandbox/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 1137, in _run_raw_task
    self._prepare_and_execute_task_with_callbacks(context, task)
  File "/home/airflow/sandbox/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 1311, in _prepare_and_execute_task_with_callbacks
    result = self._execute_task(context, task_copy)
  File "/home/airflow/sandbox/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 1341, in _execute_task
    result = task_copy.execute(context=context)
  File "/home/airflow/sandbox/lib/python3.8/site-packages/airflow/operators/bash.py", line 180, in execute
    raise AirflowException('Bash command failed. The command returned a non-zero exit code.')
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code.
[2021-12-18 15:42:04,626] {taskinstance.py:1524} INFO - Marking task as FAILED. dag_id=rank_update, task_id=make_indicator, execution_date=20211218T153907, start_date=20211218T154203, end_date=20211218T154204
[2021-12-18 15:42:04,656] {local_task_job.py:151} INFO - Task exited with return code 1
